export enum BookingStatus {
  HELD = 'HELD',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  CONFIRMED = 'CONFIRMED',
  DEFAULTED = 'DEFAULTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}
